-- MySQL Script generated by MySQL Workbench
-- Tue Feb 23 16:54:34 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fruitEtLegume
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fruitEtLegume
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fruitEtLegume` DEFAULT CHARACTER SET utf8 ;
USE `fruitEtLegume` ;

-- -----------------------------------------------------
-- Table `fruitEtLegume`.`saison`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fruitEtLegume`.`saison` (
  `idsaison` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idsaison`),
  UNIQUE INDEX `idsaison_UNIQUE` (`idsaison` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fruitEtLegume`.`mois`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fruitEtLegume`.`mois` (
  `idmois` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `saison_idsaison` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idmois`),
  UNIQUE INDEX `idmois_UNIQUE` (`idmois` ASC) VISIBLE,
  INDEX `fk_mois_saison_idx` (`saison_idsaison` ASC) VISIBLE,
  CONSTRAINT `fk_mois_saison`
    FOREIGN KEY (`saison_idsaison`)
    REFERENCES `fruitEtLegume`.`saison` (`idsaison`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fruitEtLegume`.`fruit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fruitEtLegume`.`fruit` (
  `idfruit` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `saison_idsaison` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idfruit`),
  INDEX `fk_fruit_saison1_idx` (`saison_idsaison` ASC) VISIBLE,
  CONSTRAINT `fk_fruit_saison1`
    FOREIGN KEY (`saison_idsaison`)
    REFERENCES `fruitEtLegume`.`saison` (`idsaison`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`legume`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fruitEtLegume`.`legume` (
  `idlegume` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `saison_idsaison` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idlegume`),
  INDEX `fk_legume_saison1_idx` (`saison_idsaison` ASC) VISIBLE,
  CONSTRAINT `fk_legume_saison1`
    FOREIGN KEY (`saison_idsaison`)
    REFERENCES `fruitEtLegume`.`saison` (`idsaison`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
